version: '2'

services: 
  docker-mysql:
    image: mysql:5.7.30
    container_name: mysql-spring-boot
    volumes:
      - ./data/mysql-spring:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=root
  spring-boot-jpa-docker-webapp:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: sudhakiran/gradle-springboot
    container_name: app-spring-boot
    depends_on:
      - docker-mysql
    links:
      - docker-mysql
    ports:
      - 8081:8080
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=test  
      - DATABASE_PORT=3306