<strong>Fale Conosco:</strong>

<form action='/contato' method='post' >
    
    <div class ='form-group'>
        <label>Nome</label>
        <input type='text' name='contato[nome]' class='form-control' />
    </div>
    
    <div class ='form-group'>
        <label>Email</label>
        <input type='text' name='contato[email]' class='form-control' />
    </div>
    
    <div class ='form-group'>
        <label>Mensagem</label>
        <textarea name='contato[mensagem]' class='form-control' ></textarea>
    </div>
   
    <div class ='form-group'>
        <input type='submit' value='Salvar' class='btn btn-primary' />
    </div>
   
</form>