<h1>Login</h1>

<form action='/login' method='post'>
    <div class ='form-group'>
        <label for='email'>Email</label> <input type='text' id='email' name='login[email]' class='form-control' />
        <label for='senha'>Email</label> <input type='password' id='senha' name='login[senha]' class='form-control' />
    </div>
    <div class ='form-group'>
      <input type='submit' value='Enviar' class='btn btn-primary' />
    </div>
</form>